# This is a basic workflow to help you get started with Actions

name: BigBangEvRootLess

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Cache Theos dependencies
      - name: Cache Theos
        id: cache_theos
        uses: actions/cache@v2
        with:
          path: ~/theos
          key: ${{ runner.os }}-theos-${{ hashFiles('~/theos/Prefix.pch') }}
          restore-keys: |
            ${{ runner.os }}-theos-

      # Runs a set of commands using the runners shell
      - name: Macos Env
        run: |
          brew install dpkg ldid gsed

      # Runs a set of commands using the runners shell
      - name: Theos Env
        if: steps.cache_theos.outputs.cache-hit != 'true'
        run: |
          export THEOS=~/theos
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          sudo git clone https://github.com/EvanDbg/XcodeDefaultOb.git ../XcodeDefaultOb
          cd ../XcodeDefaultOb
          sudo cat XcodeDefault.xctoolchain.zip.aa XcodeDefault.xctoolchain.zip.ab XcodeDefault.xctoolchain.zip.ac XcodeDefault.xctoolchain.zip.ad XcodeDefault.xctoolchain.zip.ae XcodeDefault.xctoolchain.zip.af XcodeDefault.xctoolchain.zip.ag XcodeDefault.xctoolchain.zip.ah XcodeDefault.xctoolchain.zip.ai XcodeDefault.xctoolchain.zip.aj > ../TweakBuilderAction/XcodeDefault.xctoolchain.zip
          cd ../TweakBuilderAction
          sudo unzip -n XcodeDefault.xctoolchain.zip -d .
          sudo mv ./XcodeDefault.xctoolchain $THEOS/toolchain/XcodeDefault1.xctoolchain
          sudo mkdir -p $THEOS/sdks/iPhoneOS14.4.sdk
          sudo cp -r ../XcodeDefaultOb/iPhoneOS14.4.sdk/* $THEOS/sdks/iPhoneOS14.4.sdk/
          sudo cp ../XcodeDefaultOb/Prefix.pch $THEOS/Prefix.pch
          sudo cp ../XcodeDefaultOb/RemoteLog.h $THEOS/include
          sudo rm -rf $THEOS/vendor/include/ControlCenterUIKit
          echo -e "\n#import <rootless.h>" >> $THEOS/Prefix.pch

      # Runs a set of commands using the runners shell
      - name: Make Clean Package
        run: |
          sudo ${{ secrets.G_CLONE_URL_BIGBANGEV }} ./BigBangEv
          cd ./BigBangEv
          sudo git checkout rootless
          # sudo bash ./build.sh
        
      # Extract the version number from control file
      # - name: Extract Release Tag
      #   shell: bash
      #   run: echo "##[set-output name=version;]$(grep Version ./BigBangEv/control | sed 's/Version:[[:space:]]//g')"
      #   id: extract_version

      # Automatic release
      # - name: Automatic Releases
      #   uses: marvinpinto/action-automatic-releases@v1.2.0
      #   with:
      #     repo_token: ${{ secrets.G_TOKEN }}
      #     automatic_release_tag: bigbangev_${{ steps.extract_version.outputs.version }}
      #     prerelease: false
      #     files: ./BigBangEv/packages/*.deb
          
      # Notify if successful
      # - name: Successful Notify
      #   run: curl https://api.day.app/HKLMhPrm4JpDq9a8QFhK9C/GithubAction/BigBangEvBuildSuccessful
