# This is a basic workflow to help you get started with Actions

name: BigBangEvRootLess

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Macos Env
        run: |
          brew install dpkg ldid gsed

      # Runs a set of commands using the runners shell
      - name: Theos Env
        if: steps.cache_theos.outputs.cache-hit != 'true'
        run: |
          export THEOS=/opt/theos
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
        # Runs a set of commands using the runners shell
      - name: Make Clean Package
        run: |
          sudo ${{ secrets.G_CLONE_URL_BIGBANGEV }} ./BigBangEv
          cd ./BigBangEv
          sudo git checkout rootless
          sudo bash ./build.sh

      - name: Extract Release Tag
        shell: bash
        run: echo "##[set-output name=version;]$(grep Version ./BigBangEv/control | sed 's/Version:[[:space:]]//g')"
        id: extract_version

      - name: Automatic Releases
        # You may pin to the exact commit or the version.
        # uses: marvinpinto/action-automatic-releases@526ce12c6675bbe6e0e9a4169c90d09a3f7ad3e2
        uses: marvinpinto/action-automatic-releases@v1.2.0
        with:
          # GitHub secret token
          repo_token: ${{ secrets.G_TOKEN }}
          automatic_release_tag: bigbangev_${{ steps.extract_version.outputs.version }}
          prerelease: false
          # Assets to upload to the release
          files: ./BigBangEv/packages/*.deb
          
      - name: Successful Notify
        run: curl https://api.day.app/HKLMhPrm4JpDq9a8QFhK9C/GithubAction/BigBangEvBuildSuccessful
