# This is a basic workflow to help you get started with Actions

name: NotiX

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Macos cache
        id: cache_macos
        uses: actions/cache@v1
        with:
          path: /usr/local
          key: ${{runner.OS}}-macos-caches

      # Runs a set of commands using the runners shell
      - name: Macos env
        run: |
          brew install dpkg ldid gsed

      - name: Theos cache
        id: cache_theos
        uses: actions/cache@v1
        with:
          path: /opt/theos
          key: ${{runner.OS}}-theos-caches

      # Runs a set of commands using the runners shell
      - name: theos env
        if: steps.cache_theos.outputs.cache-hit != 'true'
        run: |
          export THEOS=/opt/theos
          sudo mkdir -p $THEOS
          sudo git clone --recursive git://github.com/theos/theos.git $THEOS
          sudo rm -rf $THEOS/sdks/
          sudo git clone https://github.com/EvanDbg/XcodeDefaultOb.git ../XcodeDefaultOb
          cd ../XcodeDefaultOb
          sudo cat XcodeDefaultOb.xctoolchain.zip.aa XcodeDefaultOb.xctoolchain.zip.ab XcodeDefaultOb.xctoolchain.zip.ac XcodeDefaultOb.xctoolchain.zip.ad XcodeDefaultOb.xctoolchain.zip.ae XcodeDefaultOb.xctoolchain.zip.af XcodeDefaultOb.xctoolchain.zip.ag XcodeDefaultOb.xctoolchain.zip.ah XcodeDefaultOb.xctoolchain.zip.ai XcodeDefaultOb.xctoolchain.zip.aj > ../TweakBuilderAction/XcodeDefaultOb.xctoolchain.zip
          cd ../TweakBuilderAction
          sudo unzip -n XcodeDefaultOb.xctoolchain.zip -d .
          sudo mkdir $THEOS/toolchain/XcodeDefault1.xctoolchain
          sudo cp -r XcodeDefaultOb.xctoolchain/* $THEOS/toolchain/XcodeDefault1.xctoolchain/
          sudo mkdir -p $THEOS/sdks/iPhoneOS14.4.sdk
          sudo cp -r ../XcodeDefaultOb/iPhoneOS14.4.sdk/* $THEOS/sdks/iPhoneOS14.4.sdk/
          sudo cp ../XcodeDefaultOb/Prefix.pch $THEOS/Prefix.pch
          sudo cp ../XcodeDefaultOb/RemoteLog.h $THEOS/include

      - name: Extract Release Tag
        shell: bash
        run: echo "##[set-output name=version;]$(grep Version ./NotiX/layout/DEBIAN/control | sed 's/Version:[[:space:]]//g')"
        id: extract_version
