# This is a basic workflow to help you get started with Actions

name: NotiX

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Macos Env
        run: |
          brew install dpkg ldid gsed

      # Runs a set of commands using the runners shell
      - name: Theos Env
        if: steps.cache_theos.outputs.cache-hit != 'true'
        run: |
          export THEOS=/opt/theos
          sudo mkdir -p $THEOS
          sudo git clone --recursive git://github.com/theos/theos.git $THEOS
          sudo rm -rf $THEOS/sdks/
          sudo git clone https://github.com/EvanDbg/XcodeDefaultOb.git ../XcodeDefaultOb
          cd ../XcodeDefaultOb
          sudo cat XcodeDefaultOb.xctoolchain.zip.aa XcodeDefaultOb.xctoolchain.zip.ab XcodeDefaultOb.xctoolchain.zip.ac XcodeDefaultOb.xctoolchain.zip.ad XcodeDefaultOb.xctoolchain.zip.ae XcodeDefaultOb.xctoolchain.zip.af XcodeDefaultOb.xctoolchain.zip.ag XcodeDefaultOb.xctoolchain.zip.ah XcodeDefaultOb.xctoolchain.zip.ai XcodeDefaultOb.xctoolchain.zip.aj > ../TweakBuilderAction/XcodeDefaultOb.xctoolchain.zip
          cd ../TweakBuilderAction
          sudo unzip -n XcodeDefaultOb.xctoolchain.zip -d .
          sudo mkdir $THEOS/toolchain/XcodeDefault1.xctoolchain
          sudo cp -r XcodeDefaultOb.xctoolchain/* $THEOS/toolchain/XcodeDefault1.xctoolchain/
          sudo cp ../XcodeDefaultOb/Prefix.pch $THEOS/Prefix.pch
          sudo cp ../XcodeDefaultOb/RemoteLog.h $THEOS/include

        # Runs a set of commands using the runners shell
      - name: Make Clean Package
        run: |
          sudo ${{ secrets.G_CLONE_URL_NOTIX }} ./NotiX
          cd ./NotiX
          sudo cp BuildScripts/Obfuscator/Makefile Makefile
          sudo cp BuildScripts/Obfuscator/Prefs/Makefile NotiXPrefs/Makefile
          sudo cp BuildScripts/Obfuscator/build.sh build.sh
          sudo bash ./build.sh
          sudo gsed -i '/#define DPKGPATH/ c #define DPKGPATH @\"/Library/dpkg/info/fun.yfyf.beta.notix.list\"' Tweak.xm
          sudo gsed -i '/Package/ c Package: fun.yfyf.beta.notix' layout/DEBIAN/control
          sudo bash ./buildWithoutClean.sh
          sudo gsed -i '/#define DPKGPATH/ c #define DPKGPATH @\"/Library/dpkg/info/fun.yfyf.bigboss.notix.list\"' Tweak.xm
          sudo gsed -i '/Package/ c Package: fun.yfyf.bigboss.notix' layout/DEBIAN/control
          sudo bash ./buildWithoutClean.sh
          sudo gsed -i '/#define DPKGPATH/ c #define DPKGPATH @\"/Library/dpkg/info/com.hk.notix.list\"' Tweak.xm
          sudo gsed -i '/Package/ c Package: com.hk.notix' layout/DEBIAN/control
          sudo bash ./buildWithoutClean.sh
          sudo gsed -i '/#define DPKGPATH/ c #define DPKGPATH @\"/Library/dpkg/info/github.io.alierya.notix.list\"' Tweak.xm
          sudo gsed -i '/Package/ c Package: github.io.alierya.notix' layout/DEBIAN/control
          sudo chmod 777 layout/DEBIAN/control
          echo -e "\nDepiction: https://alierya.github.io/depictions/github.io.alierya.notix" >> layout/DEBIAN/control
          echo -e "\nIcon: file:///Library/PreferenceBundles/NotiXPrefs.bundle/icon@2x.png" >> layout/DEBIAN/control
          sudo bash ./buildWithoutClean.sh
          
      - name: Extract Release Tag
        shell: bash
        run: echo "##[set-output name=version;]$(grep Version ./NotiX/layout/DEBIAN/control | sed 's/Version:[[:space:]]//g')"
        id: extract_version

      - name: Automatic Releases
        # You may pin to the exact commit or the version.
        # uses: marvinpinto/action-automatic-releases@526ce12c6675bbe6e0e9a4169c90d09a3f7ad3e2
        uses: marvinpinto/action-automatic-releases@v1.2.0
        with:
          # GitHub secret token
          repo_token: ${{ secrets.G_TOKEN }}
          automatic_release_tag: notix_${{ steps.extract_version.outputs.version }}
          prerelease: false
          # Assets to upload to the release
          files: ./NotiX/packages/*.deb
          
      - name: Successful Notify
        run: curl https://api.day.app/oscvrdJCinKuuuf2dSUXhL/"Github Action"/"NotiX Build Successful"
